steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vocal-exchanger-320604/vocal-exchanger-320604:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vocal-exchanger-320604/vocal-exchanger-320604:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud' 
  args: ['run', 'deploy', 'myjavawebservice', '--region=us-central1', '--platform=managed', '--image=gcr.io/vocal-exchanger-320604/vocal-exchanger-320604:$SHORT_SHA']
  
